using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace PropertySurveyService.Models
{
    public class OKRecordDTO
    {
        public string? comments { get; set; }
        public int DBId { get; set; }
    }
    public class Header
    {
        [Key]
        public int Id { get; set; }
        public int RecID { get; set; }
        public bool bDone { get; set; }
        public bool bSent { get; set; }
        public int iRecordType { get; set; }
        public string? typeA { get; set; }
        public string? typeB { get; set; }
        public string? fit_diary { get; set; }
        public string? fitters_instructions { get; set; }
        public string? fit_start { get; set; }
        public string? fit_fin { get; set; }
        public string? fitter_work { get; set; }
        public string? parts_used { get; set; }
        public string? claim_ref { get; set; }
        public string? fitter_comments { get; set; }
        public string? udi_cont { get; set; }
        public string? sn_name { get; set; }
        public string? uc_laname { get; set; }
        public string? uc_name { get; set; }
        public string? uc_add1 { get; set; }
        public string? uc_add2 { get; set; }
        public string? uc_add3 { get; set; }
        public string? uc_add4 { get; set; }
        public string? uc_postcode { get; set; }
        public string? uc_h_phone { get; set; }
        public bool uc_goahead { get; set; }
        public string? uc_inceden { get; set; }
        public string? spare2 { get; set; }
        public double uc_excess { get; set; }
        public int bExcessCollected { get; set; }
        public int udi_tlight { get; set; }
        public int si_numitem { get; set; }
        public string? udi_inst { get; set; }
        public int alarm_cont { get; set; }
        public int ladder_req { get; set; }
        public int height_res { get; set; }
        public int sand_cemen { get; set; }
        public int plaster { get; set; }
        public int doorbell { get; set; }
        public int genreq { get; set; }
        public int architreq { get; set; }
        public int acroreq { get; set; }
        public int acrosboy { get; set; }
        public string? acc_text { get; set; }
        public int obs_wires { get; set; }
        public string? obs_wires_text { get; set; }
        public int loose_brick { get; set; }
        public string? loose_brick_text { get; set; }
        public int easy_park { get; set; }
        public int access_rear { get; set; }
        public string? rep_text { get; set; }
        public string? mop { get; set; }
        public string? card_cheq { get; set; }
        public string? expiry { get; set; }
        public int issue_no { get; set; }
        public string? reason_excess_not_collected { get; set; }
        public string? paych { get; set; }
        public string? summ_text { get; set; }
        public string? code_text { get; set; }
        public int imchup { get; set; }
        public string? job_grade { get; set; }
        public string? njs { get; set; }
        public int photo { get; set; }
        public int booked { get; set; }
        public string? nsn { get; set; }
        public string? udi_start { get; set; }
        public string? udi_fin { get; set; }
        public bool si_done { get; set; }
        public string? udi_date { get; set; }
        public string? si_bday1 { get; set; }
        public string? si_mpay { get; set; }
        public string? si_cnum { get; set; }
        public string? si_inum { get; set; }
        public string? udi_jobtext { get; set; }
        public string? udi_staff { get; set; }
        public string? type { get; set; }
        public string? sub_type { get; set; }
        public string? old_date { get; set; }
        public string? cover_instructions { get; set; }
        public string? old_start { get; set; }
        public string? old_finish { get; set; }
        public string? add_comm { get; set; }
        public string? udi_estrem { get; set; }
        public string? r_fault { get; set; }
        public int r_excess { get; set; }
        public string? rexcedit { get; set; }
        public int r_comp { get; set; }
        public string? rno_hours { get; set; }
        public string? r_work_txt { get; set; }
        public bool readditimage { get; set; }
        public string? readdtxt { get; set; }
        public bool r_sigimage { get; set; }
        public string? f_add_txt { get; set; }
        public string? fmclrf { get; set; }
        public string? fmdate { get; set; }
        public string? funfincode { get; set; }
        public string? funfinoth { get; set; }
        public string? freuntxt { get; set; }
        public string? fpartreq { get; set; }
        public bool fjobfin { get; set; }
        public string? fname1 { get; set; }
        public string? fname2 { get; set; }
        public bool fexcess { get; set; }
        public string? fexcessoth { get; set; }
        public bool fmand { get; set; }
        public string? fmandoth { get; set; }
        public string? ftimearr { get; set; }
        public string? ftimeleft { get; set; }
        public bool faddpaid { get; set; }
        public double faddmuch { get; set; }
        public string? commtxt { get; set; }
        public string? wkcartxt { get; set; }
        public string? parttxt { get; set; }
        public bool faddimage { get; set; }
        public bool fmanimage { get; set; }
        public bool fsigimage { get; set; }
        public int bWorkInside { get; set; }
        public string? inst_height { get; set; }
        public int bBothHands { get; set; }
        public string? ground_surface { get; set; }
        public string? type_of_equipment { get; set; }
        public string? risks_and_dangers { get; set; }
        public string? uc_desc { get; set; }
        public int work_at_height { get; set; }
        public int no_ladders { get; set; }
        public string? funfinished_code { get; set; }
        public string? freason_unfinished { get; set; }
        public string? fparts_required { get; set; }
        public string? ffitter_name1 { get; set; }
        public string? ffitter_name2 { get; set; }
        public int fbexcess_paid { get; set; }
        public string? freason_excess_not_paid { get; set; }
        public int fbmandate_signed { get; set; }
        public string? freason_mandate_not_signed { get; set; }
        public string? ftime_arrived { get; set; }
        public string? ftime_left { get; set; }
        public int fbadditional_paid { get; set; }
        public string? fhow_mutch_additional_paid { get; set; }
        public int bfitter_complete { get; set; }
        public int fitter_info_done { get; set; }
        public string? fbunfinother { get; set; }
        public bool bcompletion_signed { get; set; }
        public bool bad_image_complete { get; set; }
        public string? remedial_number { get; set; }
        public bool r_bsigned { get; set; }
        public string? r_bcomp { get; set; }
        public string? r_sign_date { get; set; }
        public string? stimea { get; set; }
        public string? f1_or_s2 { get; set; }
        public string? f_sign_date { get; set; }
        public long distance { get; set; }
        public long duration { get; set; }
        public int no_of_photos { get; set; }
        public string? bClosest { get; set; }
        public string? Group { get; set; }
        public string? bProcessed { get; set; }
        public int ind { get; set; }
        public string? inevitable_damage { get; set; }
        public bool fbstockusagecomplete { get; set; }
        public string? uc_h_phone2 { get; set; }
        public string? uc_h_phone3 { get; set; }
        public bool bSecuring { get; set; }
        public int ins_board { get; set; }
        public int ins_lock { get; set; }
        public int ins_temp { get; set; }
        public int ins_perm { get; set; }
        public int int_num_of_locks { get; set; }
        public string? int_type_of_lock { get; set; }
        public int parking_at_rear { get; set; }
        public int work_on_public_footpath { get; set; }
        public string? add_long { get; set; }
        public bool b_mrk { get; set; }
        public bool bSurvey { get; set; }
        public int items_above_roof { get; set; }
        public bool added_to_otherrisks { get; set; }
        public bool bMSFJob { get; set; }
        public int securing_surveyor_required { get; set; }
        public string? policy_number { get; set; }
        public bool photo_front_of_house { get; set; }
        public int asbestos_visible { get; set; }
        public string? asvizex { get; set; }
        public string? refmessage { get; set; }
        public string? uspot_fitter { get; set; }
        public string? uspot_trainee { get; set; }
        public string? uspot_date { get; set; }
        public string? uspot_customer { get; set; }
        public string? uspot_postcode { get; set; }
        public string? uspot_insuranceco { get; set; }
        public string? uspot_branch { get; set; }
        public bool uspot_repair { get; set; }
        public bool uspot_repair_arrived { get; set; }
        public bool uspot_repair_setup { get; set; }
        public bool uspot_repair_ongoing { get; set; }
        public bool uspot_repair_completed { get; set; }
        public bool uspot_replace { get; set; }
        public bool uspot_replace_arrived { get; set; }
        public bool uspot_replace_setup { get; set; }
        public bool uspot_replace_unitmoved { get; set; }
        public bool uspot_replace_completed { get; set; }
        public bool uspot_rev_door { get; set; }
        public bool uspot_rev_window { get; set; }
        public bool uspot_rev_garagedoor { get; set; }
        public bool uspot_rev_glass { get; set; }
        public bool uspot_rev_locks { get; set; }
        public bool uspot_rev_other { get; set; }
        public bool uspot_revb_upvc { get; set; }
        public bool uspot_revb_ali { get; set; }
        public bool uspot_revb_timber { get; set; }
        public bool uspot_revb_other { get; set; }
        public int uspot_appearence { get; set; }
        public string? doc_l_compliant_reason { get; set; }
        public int lintel_present { get; set; }
        public string? lintel_present_text { get; set; }
        public int uspot_customersatisfaction { get; set; }
        public string? uspot_customersatisfaction_improvementsOld { get; set; }
        public string? uspot_otherobservationsOld { get; set; }
        public bool uspot_signed { get; set; }
        public string? uspot_signeddate { get; set; }
        public bool bSpotCheck { get; set; }
        public bool uspot_replace_fit { get; set; }
        public int uspot_p1 { get; set; }
        public int uspot_p2 { get; set; }
        public int uspot_p3 { get; set; }
        public int uspot_p4 { get; set; }
        public string? uspot_appearence_improvements { get; set; }
        public string? uspot_qualityofworks_improvements { get; set; }
        public string? uspot_customersatisfaction_improvements { get; set; }
        public string? uspot_otherobservations { get; set; }
        public bool idampassword_entered { get; set; }
        public int fit_no_of_videos { get; set; }
        public int doc_l_compliant { get; set; }
        public int shop_front_work { get; set; }
        public int fitter_videos { get; set; }
        public bool is_halifax { get; set; }
        public string? messagetoinsurer { get; set; }
        public string? COD_Code { get; set; }
        public string? COD_String { get; set; }
        public bool bDamTicked { get; set; }
        public bool bSSTicked { get; set; }
        public int SSRequired { get; set; }
        public string? old_cover_instructions { get; set; }
        public string? rcodchanged { get; set; }
        public bool bcodchanged { get; set; }
        public string? goaheadstr { get; set; }
        public int b_subcontract { get; set; }
        public string? subcontracttext { get; set; }
        public bool truecomm { get; set; }
        public bool truecommconf { get; set; }
        public string? reason_not_booked_in { get; set; }
        public bool bSurveyRequiredOnSecuring { get; set; }
        public bool requiring_load_bearing_jacks { get; set; }
        public bool bSRFin { get; set; }
        public bool bMOPFin { get; set; }
        public bool bRepFin { get; set; }
        public bool bSumFin { get; set; }
        public bool bHazFin { get; set; }
        public bool bAllPictures { get; set; }
        public bool bSubFin { get; set; }
        public int total_upvc { get; set; }
        public int total_panels { get; set; }
        public int total_glass { get; set; }
        public int total_alum { get; set; }
        public int total_garage { get; set; }
        public int total_timber { get; set; }
        public int total_cons { get; set; }
        public int total_lock { get; set; }
        public int total_comp { get; set; }
        public int total_green { get; set; }
        public int total_bifold { get; set; }
        public int incomplete_upvc { get; set; }
        public int incomplete_panels { get; set; }
        public int incomplete_glass { get; set; }
        public int incomplete_alum { get; set; }
        public int incomplete_garage { get; set; }
        public int incomplete_timber { get; set; }
        public int incomplete_cons { get; set; }
        public int incomplete_lock { get; set; }
        public int incomplete_comp { get; set; }
        public int incomplete_green { get; set; }
        public int incomplete_bifold { get; set; }
        public int front_house_photos { get; set; }
        public string? time_to_complete { get; set; }
        public int current_item_number { get; set; }
        public int survey_complete { get; set; }
        public string? reason_not_complete { get; set; }
        public string? add_phone_1 { get; set; }
        public string? add_phone_2 { get; set; }
        public int no_of_fitters { get; set; }
        public string? fname3 { get; set; }
        public string? fname4 { get; set; }
        public string? fname5 { get; set; }
        public string? fname6 { get; set; }
        public string? fname7 { get; set; }
        public string? fname8 { get; set; }
        public int ownquote { get; set; }
        public int survey_on_fit { get; set; }
        public int i_spare1 { get; set; }
        public int i_spare2 { get; set; }
        public int i_spare3 { get; set; }
        public string? s_spare1 { get; set; }
        public string? s_spare2 { get; set; }
        public string? s_spare3 { get; set; }
        public int new_ispare1 { get; set; }
        public int new_ispare2 { get; set; }
        public int new_ispare3 { get; set; }
        public int new_ispare4 { get; set; }
        public int new_ispare5 { get; set; }
        public int new_ispare6 { get; set; }
        public int new_ispare7 { get; set; }
        public int new_ispare8 { get; set; }
        public int new_ispare9 { get; set; }
        public int is_messagetoinsurer { get; set; }
        public string? new_sspare1 { get; set; }
        public string? new_sspare2 { get; set; }
        public string? new_sspare3 { get; set; }
        public string? new_sspare4 { get; set; }
        public string? new_sspare5 { get; set; }
        public string? new_sspare6 { get; set; }
        public string? new_sspare7 { get; set; }
        public string? new_sspare8 { get; set; }
        public string? new_sspare9 { get; set; }
        public string? new_sspare10 { get; set; }

        public bool bInfoSeen { get; set; }

        public int ss_bIsSecuritySurvey { get; set; }
        public int ss_bIsComplete { get; set; }
        public string? ss_nowindows { get; set; }
        public string? ss_nodoors { get; set; }
        public string? ss_gencondition { get; set; }
        public string? ss_gencondition_other { get; set; }
        public string? ss_matwindows { get; set; }
        public string? ss_matwindows_other { get; set; }
        public string? ss_matdoors { get; set; }
        public string? ss_matdoors_other { get; set; }
        public string? ss_lockwindows { get; set; }
        public string? ss_lockwindows_other { get; set; }
        public string? ss_lockdoors { get; set; }
        public string? ss_lockdoors_other { get; set; }
        public int ss_add_window_security { get; set; }
        public string? ss_location_windows_other { get; set; }
        public string? ss_secwindows_other { get; set; }
        public int ss_add_door_security { get; set; }
        public string? ss_location_doors_other { get; set; }
        public string? ss_secdoors_other { get; set; }
        public string? ss_time_required { get; set; }

        public int ss_no_of_photos { get; set; }
        public string? door_type { get; set; }
        public string? model_type { get; set; }
        public string? unique_serial { get; set; }
        public string? door_size { get; set; }
        public string? door_manufacturer { get; set; }
        public string? powerered_operator_type { get; set; }
        public string? operator_manufacturer { get; set; }
        public string? site_address { get; set; }
        public string? decleration_by { get; set; }
        public string? on_behalf_of_person { get; set; }
        public string? on_behalf_of_company { get; set; }
        public string? decleration_received_by { get; set; }
        public string? date { get; set; }
        public string? print_name { get; set; }
        public string? date_cust { get; set; }
        public int i_signed { get; set; }
        public int i_signed_cust { get; set; }

        public int directive_complete { get; set; }

        public string? branch { get; set; }
        public string? name { get; set; }
        public string? job { get; set; }
        public string? name1 { get; set; }
        public int safety_boots_worn1 { get; set; }
        public int safety_gloves_worn1 { get; set; }
        public int safety_googles_worn1 { get; set; }
        public int safety_helmet_worn1 { get; set; }
        public int wristguards_worn1 { get; set; }
        public int uniform_worn_complete1 { get; set; }
        public int id_card_available1 { get; set; }
        public string? name2 { get; set; }
        public int safety_boots_worn2 { get; set; }
        public int safety_gloves_worn2 { get; set; }
        public int safety_googles_worn2 { get; set; }
        public int safety_helmet_worn2 { get; set; }
        public int wristguards_worn2 { get; set; }
        public int uniform_worn_complete2 { get; set; }
        public int id_card_available2 { get; set; }
        public int chemicals_stored_correctly { get; set; }
        public int are_sheets_available { get; set; }
        public int area_above_been_checked { get; set; }
        public int obstructions_checked { get; set; }
        public int lintel_ok { get; set; }
        public int ladders_secure { get; set; }
        public int safe_work_at_height { get; set; }
        public int condition_of_ladders { get; set; }
        public int tools_set_out_safely { get; set; }
        public int fire_extinguisher_on_van { get; set; }
        public int first_aid_kit_on_van { get; set; }
        public int electrical_equipment_tested { get; set; }
        public string? safety_boots_worn1_s { get; set; }
        public string? safety_gloves_worn1_s { get; set; }
        public string? safety_googles_worn1_s { get; set; }
        public string? safety_helmet_worn1_s { get; set; }
        public string? wristguards_worn1_s { get; set; }
        public string? uniform_worn_complete1_s { get; set; }
        public string? id_card_available1_s { get; set; }
        public string? safety_boots_worn2_s { get; set; }
        public string? safety_gloves_worn2_s { get; set; }
        public string? safety_googles_worn2_s { get; set; }
        public string? safety_helmet_worn2_s { get; set; }
        public string? wristguards_worn2_s { get; set; }
        public string? uniform_worn_complete2_s { get; set; }
        public string? id_card_available2_s { get; set; }
        public string? chemicals_stored_correctly_s { get; set; }
        public string? are_sheets_available_s { get; set; }
        public string? area_above_been_checked_s { get; set; }
        public string? obstructions_checked_s { get; set; }
        public string? lintel_ok_s { get; set; }
        public string? ladders_secure_s { get; set; }
        public string? safe_work_at_height_s { get; set; }
        public string? condition_of_ladders_s { get; set; }
        public string? tools_set_out_safely_s { get; set; }
        public string? fire_extinguisher_on_van_s { get; set; }
        public string? first_aid_kit_on_van_s { get; set; }
        public string? electrical_equipment_tested_s { get; set; }
        public string? comments { get; set; }
        public int uspot_qualityofworks { get; set; }
        public int current_summary_num { get; set; }

        public int uspot_replacement { get; set; }

        public int garage_door_motor { get; set; }

        public int isTowerScaff { get; set; }

    }


    }
