using SQLite;
namespace PropertySurvey
{
    public class DamageLabels
    {
        [PrimaryKey, AutoIncrement]
        public int RecID { get; set; }
        public int item_no { get; set; }
        public int pos_x { get; set; }
        public int pos_y { get; set; }
        public int label_type { get; set; }     // 1- Scratch 2- Dent 3- Hole
        public int angle_num { get; set; }      // 1- Passenger 2- Driver 3- Front 4- Rear
        public string vehicle_type { get; set; }  // van , car , delivery , 
        public string vehicle_reg { get; set; }
        public string CheckID { get; set; }
        public string check_date { get; set; }
    }

    public class VanChecksHeader
    {
        [PrimaryKey, AutoIncrement]
        public int RecID { get; set; }
        public string check_date { get; set; }
        public string name { get; set; }
        public string PDACode { get; set; }
        public bool bComplete { get; set; }
        public bool bSent { get; set; }
        public int current_item_no { get; set; }
        public int total_delivery { get; set; }
        public int total_delivery_van { get; set; }
        public int total_vans { get; set; }
        public int total_cars { get; set; }
        public int total_incomplete_delivery { get; set; }
        public int total_incomplete_delivery_van { get; set; }
        public int total_incomplete_vans { get; set; }
        public int total_incomplete_cars { get; set; }
        public string unique_id { get; set; } // consists of date, pda code, and unique Van Check ID number
        public string damage_pass { get; set; }
        public string damage_driver { get; set; }
        public string damage_front { get; set; }
        public string damage_back { get; set; }
        public string spare_s_1 { get; set; }  // branch code
        public string spare_s_2 { get; set; }
        public string spare_s_3 { get; set; }
        public string spare_s_4 { get; set; }
        public int spare_i_1 { get; set; }
        public int spare_i_2 { get; set; }  // No of additional photos
        public int spare_i_3 { get; set; }
        public int spare_i_4 { get; set; }
        public int new_ispare1 { get; set; } // Cill on subframe
        public int new_ispare2 { get; set; } // Cill type
        public int new_ispare3 { get; set; }
        public int new_ispare4 { get; set; }
        public int new_ispare5 { get; set; }
        public int new_ispare6 { get; set; }
        public int new_ispare7 { get; set; }
        public int new_ispare8 { get; set; }
        public int new_ispare9 { get; set; }
        public int new_ispare10 { get; set; }
        public string new_sspare1 { get; set; }
        public string new_sspare2 { get; set; }
        public string new_sspare3 { get; set; }
        public string new_sspare4 { get; set; }
        public string new_sspare5 { get; set; }
        public string new_sspare6 { get; set; }
        public string new_sspare7 { get; set; }
        public string new_sspare8 { get; set; }
        public string new_sspare9 { get; set; }
        public string new_sspare10 { get; set; }
    }
    public class DeliveryVanVehicleCheckList // HGV
    {
        [PrimaryKey, AutoIncrement]
        public int RecID { get; set; }
        public string CheckID { get; set; }
        public int item_no { get; set; }
        public string item_no_4D { get; set; }
        public string name { get; set; }
        public string destination { get; set; }
        public string date { get; set; }
        public string vehicle_registration { get; set; }
        public string mileage { get; set; }
        public int ats_card { get; set; }
        public int bodywork_check { get; set; }
        public int breakdown_card { get; set; }
        public int clean_external { get; set; }
        public int clean_internal { get; set; }
        public int fan_belt { get; set; }
        public int fire_extinguisher { get; set; }
        public int first_aid_box { get; set; }
        public int fuel_card { get; set; }
        public int horn { get; set; }
        public int jack { get; set; }
        public int jump_leads { get; set; }
        public int keys_for_branches { get; set; }
        public int lights_inducators { get; set; }
        public int oil_water_checked { get; set; }
        public int racks_poles { get; set; }
        public int ratchet_straps { get; set; }
        public int receipt_book { get; set; }
        public int bump_hats { get; set; }
        public int service_due_sticker { get; set; }
        public int spanners_for_rack_removal { get; set; }
        public int spare_oil { get; set; }
        public int coolant_anti_freeze_mix { get; set; }
        public int spare_wheel { get; set; }
        public int tow_ropes { get; set; }
        public int tyre_pressure { get; set; }
        public int van_height_sticker { get; set; }
        public int van_locks { get; set; }
        public int wheel_nut_check_sticker { get; set; }
        public int wheelbrace { get; set; }
        public int windscreen_washer { get; set; }
        public int pda_phone_accident_pack { get; set; }
        public int branch_keys { get; set; }
        public string ats_card_s { get; set; }
        public string bodywork_check_s { get; set; }
        public string breakdown_card_s { get; set; }
        public string clean_external_s { get; set; }
        public string clean_internal_s { get; set; }
        public string fan_belt_s { get; set; }
        public string fire_extinguisher_s { get; set; }
        public string first_aid_box_s { get; set; }
        public string fuel_card_s { get; set; }
        public string horn_s { get; set; }
        public string jack_s { get; set; }
        public string jump_leads_s { get; set; }
        public string keys_for_branches_s { get; set; }
        public string lights_inducators_s { get; set; }
        public string oil_water_checked_s { get; set; }
        public string racks_poles_s { get; set; }
        public string ratchet_straps_s { get; set; }
        public string receipt_book_s { get; set; }
        public string bump_hats_s { get; set; }
        public string service_due_sticker_s { get; set; }
        public string spanners_for_rack_removal_s { get; set; }
        public string spare_oil_s { get; set; }
        public string coolant_anti_freeze_mix_s { get; set; }
        public string spare_wheel_s { get; set; }
        public string tow_ropes_s { get; set; }
        public string tyre_pressure_s { get; set; }
        public string van_height_sticker_s { get; set; }
        public string van_locks_s { get; set; }
        public string wheel_nut_check_sticker_s { get; set; }
        public string wheelbrace_s { get; set; }
        public string windscreen_washer_s { get; set; }
        public string pda_phone_accident_pack_s { get; set; }
        public string branch_keys_s { get; set; }
        public int passenger_front_pressure { get; set; } // Yes or No correct pressure
        public int passenger_rear_pressure { get; set; }
        public int driver_front_pressure { get; set; }
        public int driver_rear_pressure { get; set; }
        public int spare_tyre_pressure { get; set; }
        public string passenger_front_pressure_s { get; set; } // Yes or No correct pressure
        public string passenger_rear_pressure_s { get; set; }
        public string driver_front_pressure_s { get; set; }
        public string driver_rear_pressure_s { get; set; }
        public string spare_tyre_pressure_s { get; set; }
        public bool bDriverSigned { get; set; }
        public bool bCheckedBySigned { get; set; }
        public string driver_printed { get; set; }
        public string checked_printed { get; set; }
        public bool bDespatchManagerSigned { get; set; }
        public int photos_front { get; set; }
        public int photos_rear { get; set; }
        public int photos_left { get; set; }
        public int photos_right { get; set; }
        public bool bDataEntered { get; set; }
        public bool bComplete { get; set; }
        public bool bSent { get; set; }
        public string damage_pass { get; set; }
        public string damage_driver { get; set; }
        public string damage_front { get; set; }
        public string damage_back { get; set; }
        public int is_complete { get; set; }
        public string not_complete_reason { get; set; }
        public string spare_s_1 { get; set; } // Shell Fuel Card
        public string spare_s_2 { get; set; }
        public string spare_s_3 { get; set; }
        public string spare_s_4 { get; set; }
        public int spare_i_1 { get; set; }
        public int spare_i_2 { get; set; }// No of additional photos
        public int spare_i_3 { get; set; }
        public int spare_i_4 { get; set; }
        public bool bPhotosComplete { get; set; }
        public bool bDiagramsComplete { get; set; }
        public bool bSignaturesComplete { get; set; }
        public int new_ispare1 { get; set; } // Cill on subframe
        public int new_ispare2 { get; set; } // Cill type
        public int new_ispare3 { get; set; }
        public int new_ispare4 { get; set; }
        public int new_ispare5 { get; set; }
        public int new_ispare6 { get; set; }
        public int new_ispare7 { get; set; }
        public int new_ispare8 { get; set; }
        public int new_ispare9 { get; set; }
        public int new_ispare10 { get; set; }
        public string new_sspare1 { get; set; }
        public string new_sspare2 { get; set; }
        public string new_sspare3 { get; set; }
        public string new_sspare4 { get; set; }
        public string new_sspare5 { get; set; }
        public string new_sspare6 { get; set; }
        public string new_sspare7 { get; set; }
        public string new_sspare8 { get; set; }
        public string new_sspare9 { get; set; }
        public string new_sspare10 { get; set; }

    }
    public class DeliveryVehicleCheckList // HGV
    {
        [PrimaryKey, AutoIncrement]
        public int RecID { get; set; }
        public string CheckID { get; set; }
        public int item_no { get; set; }
        public string item_no_4D { get; set; }
        public string name { get; set; }
        public string destination { get; set; }
        public string date { get; set; }
        public string vehicle_registration { get; set; }
        public string mileage { get; set; }
        public int ats_card { get; set; }
        public int national_tyres_card { get; set; }
        public int fmg_support_sticker { get; set; }
        public int fuel_card { get; set; }
        public int clean_external { get; set; }
        public int clean_internal { get; set; }
        public int fan_belt { get; set; }
        public int fire_extinguisher { get; set; }
        public int first_aid_box { get; set; }
        public int horn { get; set; }
        public int oil_and_water_checked { get; set; }
        public int accident_pack { get; set; }
        public int portable_lighting { get; set; }
        public int ad_blue_level_check { get; set; }
        public int racks_and_poles { get; set; }
        public int ratchet_straps { get; set; }
        public int service_due_sticker { get; set; }
        public int no_smoking_sticker { get; set; }
        public int spare_oil { get; set; }
        public int coolant_anti_freez { get; set; }
        public int tyre_pressure { get; set; }
        public int van_height_sticker { get; set; }
        public int van_locks { get; set; }
        public int wheel_nut_check_sticker { get; set; }
        public int windscreen_washer { get; set; }
        public int fuel_oil_leaks { get; set; }
        public int battery_security_condition { get; set; }
        public int tyres_and_wheel_fixing { get; set; }
        public int spray_suppression { get; set; }
        public int steering { get; set; }
        public int security_of_load { get; set; }
        public int mirrors { get; set; }
        public int lights { get; set; }
        public int reflectors { get; set; }
        public int inducators { get; set; }
        public int wipers { get; set; }
        public int washers { get; set; }
        public int horn_comp { get; set; }
        public int excessive_exhaust_smoke { get; set; }
        public int brakes { get; set; }
        public int security_of_body { get; set; }
        public int markers { get; set; }
        public int glass_windscreen { get; set; }
        public int receipt_book { get; set; }
        public int keys_for_branches_sat { get; set; }
        public int pda_phone_accident_pack { get; set; }
        public int trade_invoices { get; set; }
        public int blue_bags { get; set; }
        public int delivery_lists { get; set; }
        public int collection_lists { get; set; }
        public int trade_delivery_notes { get; set; }
        public string report_defects { get; set; }
        public string date_signed { get; set; }
        public int passenger_front_pressure { get; set; } // Yes or No correct pressure
        public int passenger_rear_pressure { get; set; }
        public int driver_front_pressure { get; set; }
        public int driver_rear_pressure { get; set; }
        public int spare_tyre_pressure { get; set; }
        public string passenger_front_pressure_s { get; set; } // Yes or No correct pressure
        public string passenger_rear_pressure_s { get; set; }
        public string driver_front_pressure_s { get; set; }
        public string driver_rear_pressure_s { get; set; }
        public string spare_tyre_pressure_s { get; set; }
        public bool bDriverSigned { get; set; }
        public bool bCheckedBySigned { get; set; }
        public string driver_printed { get; set; }
        public string checked_printed { get; set; }
        public bool bDespatchManagerSigned { get; set; }
        public int photos_front { get; set; }
        public int photos_rear { get; set; }
        public int photos_left { get; set; }
        public int photos_right { get; set; }
        public bool bDataEntered { get; set; }
        public bool bComplete { get; set; }
        public bool bSent { get; set; }
        public string damage_pass { get; set; }
        public string damage_driver { get; set; }
        public string damage_front { get; set; }
        public string damage_back { get; set; }
        public int is_complete { get; set; }
        public string not_complete_reason { get; set; }
        public string spare_s_1 { get; set; } // Shell fuel card
        public string spare_s_2 { get; set; }
        public string spare_s_3 { get; set; }
        public string spare_s_4 { get; set; }
        public int spare_i_1 { get; set; }
        public int spare_i_2 { get; set; }// No of additional photos
        public int spare_i_3 { get; set; }
        public int spare_i_4 { get; set; }
        public bool bPhotosComplete { get; set; }
        public bool bDiagramsComplete { get; set; }
        public bool bSignaturesComplete { get; set; }
        public int new_ispare1 { get; set; } // Cill on subframe
        public int new_ispare2 { get; set; } // Cill type
        public int new_ispare3 { get; set; }
        public int new_ispare4 { get; set; }
        public int new_ispare5 { get; set; }
        public int new_ispare6 { get; set; }
        public int new_ispare7 { get; set; }
        public int new_ispare8 { get; set; }
        public int new_ispare9 { get; set; }
        public int new_ispare10 { get; set; }
        public string new_sspare1 { get; set; }
        public string new_sspare2 { get; set; }
        public string new_sspare3 { get; set; }
        public string new_sspare4 { get; set; }
        public string new_sspare5 { get; set; }
        public string new_sspare6 { get; set; }
        public string new_sspare7 { get; set; }
        public string new_sspare8 { get; set; }
        public string new_sspare9 { get; set; }
        public string new_sspare10 { get; set; }
    }
    public class WeeklyVanCheckSheet
    {
        [PrimaryKey, AutoIncrement]
        public int RecID { get; set; }
        public string CheckID { get; set; }
        public string branch { get; set; }
        public string reg_no { get; set; }
        public string date { get; set; }
        public string mileage { get; set; }
        public int item_no { get; set; }
        public string item_no_4D { get; set; }
        public int circuit_breaker { get; set; }
        public int power_breaker { get; set; }
        public int hammer_drill { get; set; }
        public int ordinary_drill { get; set; }
        public int cordless_drill { get; set; }
        public int spare_battery_and_charger { get; set; }
        public int circular_saw { get; set; }
        public int jig_saw { get; set; }
        public int planer_check_blade { get; set; }
        public int heat_gun { get; set; }
        public int sander { get; set; }
        public int hoover { get; set; }
        public int halogen_lamp { get; set; }
        public int extension_lead { get; set; }
        public int router { get; set; }
        public int industrial_ladders { get; set; }
        public int ladder_clamps { get; set; }
        public int step_ladders { get; set; }
        public int ladder_stopper { get; set; }
        public int philips_bit { get; set; }
        public int screw_box { get; set; }
        public int tresles_x2 { get; set; }
        public int torch_working { get; set; }
        public int ratchett_straps_x4 { get; set; }
        public int spare_wheel { get; set; }
        public int blue_external_dust_sheet { get; set; }
        public int internal_dust_sheets_x3 { get; set; }
        public int brush_and_shovel { get; set; }
        public int cleaner_bottle { get; set; }
        public int ecloth { get; set; }
        public int mastic_guns { get; set; }
        public int glass_suckers { get; set; }
        public int safety_helmets { get; set; }
        public int helmet_manufacture_date { get; set; }
        public int gloves { get; set; }
        public int wrist_guards { get; set; }
        public int goggles { get; set; }
        public int ear_defenders { get; set; }
        public int dust_masks { get; set; }
        public int customer_care_cards { get; set; }
        public int completion_forms { get; set; }
        public int freepost_envelopes { get; set; }
        public int mandate_forms { get; set; }
        public int quality_manuals { get; set; }
        public int stapler { get; set; }
        public int worksheets { get; set; }
        public int plasters { get; set; }
        public int dressing { get; set; }
        public int eyewashers { get; set; }
        public int steri_wipes { get; set; }
        public int bag { get; set; }
        public int flexi_meter { get; set; }
        public int merlin_low_e_detector { get; set; }
        public int cabin_condition { get; set; }
        public int national_tyres_card { get; set; }
        public int breakdown_card { get; set; }
        public int fuel_card { get; set; }
        public int shell_points_card { get; set; }
        public int fire_extinguisher { get; set; }
        public int jack { get; set; }
        public int wheelbrace { get; set; }
        public int jump_leads { get; set; }
        public int fan_belt { get; set; }
        public int tow_ropes { get; set; }
        public int spare_oil { get; set; }
        public int coolant_anti_freeze { get; set; }
        public int van_height_sticker { get; set; }
        public int wheel_nut_check_sticker { get; set; }
        public int no_smoking_sticker { get; set; }
        public int racks_and_poles { get; set; }
        public int tyre_conditions { get; set; }
        public int van_locks { get; set; }
        public int oil_and_water_checked { get; set; }
        public int hows_my_driving_sticker { get; set; }
        public int pda_setup_date { get; set; }
        public int accident_pack_on_pda { get; set; }
        public int hi_vis_vests { get; set; }
        public int grinder { get; set; }
        public int windscreen_good_contidion { get; set; }
        public string circuit_breaker_s { get; set; }
        public string power_breaker_s { get; set; }
        public string hammer_drill_s { get; set; }
        public string ordinary_drill_s { get; set; }
        public string cordless_drill_s { get; set; }
        public string spare_battery_and_charger_s { get; set; }
        public string circular_saw_s { get; set; }
        public string jig_saw_s { get; set; }
        public string planer_check_blade_s { get; set; }
        public string heat_gun_s { get; set; }
        public string sander_s { get; set; }
        public string hoover_s { get; set; }
        public string halogen_lamp_s { get; set; }
        public string extension_lead_s { get; set; }
        public string router_s { get; set; }
        public string industrial_ladders_s { get; set; }
        public string ladder_clamps_s { get; set; }
        public string step_ladders_s { get; set; }
        public string ladder_stopper_s { get; set; }
        public string philips_bit_s { get; set; }
        public string screw_box_s { get; set; }
        public string tresles_x2_s { get; set; }
        public string torch_working_s { get; set; }
        public string ratchett_straps_x4_s { get; set; }
        public string spare_wheel_s { get; set; }
        public string blue_external_dust_sheet_s { get; set; }
        public string internal_dust_sheets_x3_s { get; set; }
        public string brush_and_shovel_s { get; set; }
        public string cleaner_bottle_s { get; set; }
        public string ecloth_s { get; set; }
        public string mastic_guns_s { get; set; }
        public string glass_suckers_s { get; set; }
        public string safety_helmets_s { get; set; }
        public string helmet_manufacture_date_s { get; set; }
        public string gloves_s { get; set; }
        public string wrist_guards_s { get; set; }
        public string goggles_s { get; set; }
        public string ear_defenders_s { get; set; }
        public string dust_masks_s { get; set; }
        public string customer_care_cards_s { get; set; }
        public string completion_forms_s { get; set; }
        public string freepost_envelopes_s { get; set; }
        public string mandate_forms_s { get; set; }
        public string quality_manuals_s { get; set; }
        public string stapler_s { get; set; }
        public string worksheets_s { get; set; }
        public string plasters_s { get; set; }
        public string dressing_s { get; set; }
        public string eyewashers_s { get; set; }
        public string steri_wipes_s { get; set; }
        public string bag_s { get; set; }
        public string flexi_meter_s { get; set; }
        public string merlin_low_e_detector_s { get; set; }
        public string cabin_condition_s { get; set; }
        public string national_tyres_card_s { get; set; }
        public string breakdown_card_s { get; set; }
        public string fuel_card_s { get; set; }
        public string shell_points_card_s { get; set; }
        public string fire_extinguisher_s { get; set; }
        public string jack_s { get; set; }
        public string wheelbrace_s { get; set; }
        public string jump_leads_s { get; set; }
        public string fan_belt_s { get; set; }
        public string tow_ropes_s { get; set; }
        public string spare_oil_s { get; set; }
        public string coolant_anti_freeze_s { get; set; }
        public string van_height_sticker_s { get; set; }
        public string wheel_nut_check_sticker_s { get; set; }
        public string no_smoking_sticker_s { get; set; }
        public string racks_and_poles_s { get; set; }
        public string tyre_conditions_s { get; set; }
        public string van_locks_s { get; set; }
        public string oil_and_water_checked_s { get; set; }
        public string hows_my_driving_sticker_s { get; set; }
        public string pda_setup_date_s { get; set; }
        public string accident_pack_on_pda_s { get; set; }
        public string hi_vis_vests_s { get; set; }
        public string grinder_s { get; set; }
        public string windscreen_good_contidion_s { get; set; }
        public int fitters_own_power_tools_ladders_on_van { get; set; }
        public string marks_out_of_10 { get; set; }
        // Panel Check Sheet
        public string panel_date;
        public string vehicle_reg { get; set; }
        public int passenger_front_pressure { get; set; } // Yes or No correct pressure
        public int passenger_rear_pressure { get; set; }
        public int driver_front_pressure { get; set; }
        public int driver_rear_pressure { get; set; }
        public int spare_tyre_pressure { get; set; }
        public string passenger_front_pressure_s { get; set; } // Yes or No correct pressure
        public string passenger_rear_pressure_s { get; set; }
        public string driver_front_pressure_s { get; set; }
        public string driver_rear_pressure_s { get; set; }
        public string spare_tyre_pressure_s { get; set; }
        public string driver_name { get; set; }
        public string van_check_name { get; set; }
        public bool bDriverSigned { get; set; }
        public bool bCheckedBySigned { get; set; }
        public string driver_printed { get; set; }
        public string checked_printed { get; set; }
        public int photos_front { get; set; }
        public int photos_rear { get; set; }
        public int photos_left { get; set; }
        public int photos_right { get; set; }
        public bool bDataEntered { get; set; }
        public bool bComplete { get; set; }
        public bool bSent { get; set; }
        public string damage_pass { get; set; }
        public string damage_driver { get; set; }
        public string damage_front { get; set; }
        public string damage_back { get; set; }
        public int is_complete { get; set; }
        public string not_complete_reason { get; set; }
        public string spare_s_1 { get; set; } // Shell fuel card
        public string spare_s_2 { get; set; }
        public string spare_s_3 { get; set; }
        public string spare_s_4 { get; set; }
        public int spare_i_1 { get; set; }
        public int spare_i_2 { get; set; }// No of additional photos
        public int spare_i_3 { get; set; } // DiagramsViewed 0 = no
        public int spare_i_4 { get; set; }
        public string ManufactureDateOnHelmet { get; set; }
        public string PDASetupDate { get; set; }
        public bool bPhotosComplete { get; set; }
        public bool bDiagramsComplete { get; set; }
        public bool bSignaturesComplete { get; set; }
        public string ManufactureDateOnHelmet2 { get; set; }
        public string ManufactureDateOnHelmet3 { get; set; }
        public string ManufactureDateOnHelmet4 { get; set; }
        public string ManufactureDateOnHelmet5 { get; set; }
        public string ManufactureDateOnHelmet6 { get; set; }
        public string ManufactureDateOnHelmet7 { get; set; }
        public string ManufactureDateOnHelmet8 { get; set; }
        public string ManufactureDateOnHelmet9 { get; set; }
        public string ManufactureDateOnHelmet10 { get; set; }
        public string idcard1 { get; set; }
        public string idcard2 { get; set; }
        public string idcard3 { get; set; }
        public int new_ispare1 { get; set; } // Cill on subframe
        public int new_ispare2 { get; set; } // Cill type
        public int new_ispare3 { get; set; }
        public int new_ispare4 { get; set; }
        public int new_ispare5 { get; set; }
        public int new_ispare6 { get; set; }
        public int new_ispare7 { get; set; }
        public int new_ispare8 { get; set; }
        public int new_ispare9 { get; set; }
        public int new_ispare10 { get; set; }
        public string new_sspare1 { get; set; }
        public string new_sspare2 { get; set; }
        public string new_sspare3 { get; set; }
        public string new_sspare4 { get; set; }
        public string new_sspare5 { get; set; }
        public string new_sspare6 { get; set; }
        public string new_sspare7 { get; set; }
        public string new_sspare8 { get; set; }
        public string new_sspare9 { get; set; }
        public string new_sspare10 { get; set; }
    }
    public class CarPanelSheet
    {
        [PrimaryKey, AutoIncrement]
        public int RecID { get; set; }
        public string CheckID { get; set; }
        public int item_no { get; set; }
        public string item_no_4D { get; set; }
        public string vehicle_reg { get; set; }
        public string date { get; set; }
        public bool driver_signed { get; set; }
        public string driver_printed { get; set; }
        public bool checked_signed { get; set; }
        public string checked_printed { get; set; }
        public string mileage { get; set; }
        public int fuel_card { get; set; }
        public int shell_points_card { get; set; }
        public int interior_clean { get; set; }
        public int oil_level { get; set; }
        public int water_level { get; set; }
        public int windscreen_wash { get; set; }
        public int spare_wheel { get; set; }
        public int jack { get; set; }
        public int wheel_brace { get; set; }
        public int tools { get; set; }
        public int tyre_condition { get; set; }
        public string fuel_card_s { get; set; }
        public string shell_points_card_s { get; set; }
        public string interior_clean_s { get; set; }
        public string oil_level_s { get; set; }
        public string water_level_s { get; set; }
        public string windscreen_wash_s { get; set; }
        public string spare_wheel_s { get; set; }
        public string jack_s { get; set; }
        public string wheel_brace_s { get; set; }
        public string tools_s { get; set; }
        public string tyre_condition_s { get; set; }
        public int pressure_passenger_front { get; set; }
        public int pressure_passenger_rear { get; set; }
        public int pressure_driver_front { get; set; }
        public int pressure_driver_rear { get; set; }
        public int spare_tyre_pressure { get; set; }
        public string pressure_passenger_front_s { get; set; }
        public string pressure_passenger_rear_s { get; set; }
        public string pressure_driver_front_s { get; set; }
        public string pressure_driver_rear_s { get; set; }
        public string spare_tyre_pressure_s { get; set; }
        public bool bDriverSigned { get; set; }
        public bool bCheckedBySigned { get; set; }
        public int photos_front { get; set; }
        public int photos_rear { get; set; }
        public int photos_left { get; set; }
        public int photos_right { get; set; }
        public bool bDataEntered { get; set; }
        public bool bComplete { get; set; }
        public bool bSent { get; set; }
        public string damage_pass { get; set; }
        public string damage_driver { get; set; }
        public string damage_front { get; set; }
        public string damage_back { get; set; }
        public int is_complete { get; set; }
        public string not_complete_reason { get; set; }
        public string shell_fuel_card_s { get; set; }  // Shell fuel card
        public string spare_s_2 { get; set; } // Loading storage floor good condt
        public string spare_s_3 { get; set; }
        public string spare_s_4 { get; set; }
        public int shell_fuel_card { get; set; }
        public int spare_i_2 { get; set; } // Loading storage floor good condt
        public int spare_i_3 { get; set; }
        public int spare_i_4 { get; set; }
        public bool bPhotosComplete { get; set; }
        public bool bDiagramsComplete { get; set; }
        public bool bSignaturesComplete { get; set; }
        public int new_ispare1 { get; set; } // Cill on subframe
        public int new_ispare2 { get; set; } // Cill type
        public int new_ispare3 { get; set; }
        public int new_ispare4 { get; set; }
        public int new_ispare5 { get; set; }
        public int new_ispare6 { get; set; }
        public int new_ispare7 { get; set; }
        public int new_ispare8 { get; set; }
        public int new_ispare9 { get; set; }
        public int new_ispare10 { get; set; }
        public string new_sspare1 { get; set; }
        public string new_sspare2 { get; set; }
        public string new_sspare3 { get; set; }
        public string new_sspare4 { get; set; }
        public string new_sspare5 { get; set; }
        public string new_sspare6 { get; set; }
        public string new_sspare7 { get; set; }
        public string new_sspare8 { get; set; }
        public string new_sspare9 { get; set; }
        public string new_sspare10 { get; set; }
    }
}
